[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mergendb"
version = "0.8.2"
description = "Ultra-compact, columnar, embedded database engine and custom query language (MergenQL) designed to run large workloads on small hardware."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
    { name = "Uğur Türker Kebeci", email = "ugurturkerkebeci@users.noreply.github.com" }
]
maintainers = [
    { name = "Uğur Türker Kebeci", email = "ugurturkerkebeci@users.noreply.github.com" }
]
keywords = [
    "database",
    "columnar",
    "compression",
    "embedded",
    "edge-computing",
    "query-engine",
    "analytics",
    "sql",
    "mergenql"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Database",
    "Topic :: Database :: Database Engines/Servers",
    "Topic :: Scientific/Engineering :: Information Analysis"
]

[project.optional-dependencies]
studio = ["mergendb-studio>=0.7.0"]

[project.urls]
"Homepage" = "https://github.com/ugurturkerkebeci/MergenDB"
"Repository" = "https://github.com/ugurturkerkebeci/MergenDB.git"
"Bug Tracker" = "https://github.com/ugurturkerkebeci/MergenDB/issues"
"Documentation" = "https://github.com/ugurturkerkebeci/MergenDB#readme"

[project.scripts]
mergen = "mergendb.cli.repl:main"
mergendb = "mergendb.cli.repl:main"
mergendb-server = "mergendb.server.server:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["mergendb*"]
